[server]
host = "localhost"
port = 9240

[coordinator]
# Sequential, Parallel, DependencyBased
mode = "Sequential"
db_url = "configs/wattle.db"

[database]
max_connections = 50
connection_timeout_secs = 20
