# Wattle Scheduler 完整配置示例
# 所有配置项都是可选的，未设置的项将使用默认值

[server]
# 服务器监听地址
host = "localhost"
# 服务器端口
port = 9240
# CORS 允许的源，多个用逗号分隔
cors_origins = "*,http://localhost:3000,https://example.com"
# 请求超时时间（秒）
request_timeout_secs = 30

[coordinator]
# 协调器模式：Sequential（顺序）、Parallel（并行）、DependencyBased（基于依赖）
mode = "Sequential"
# 数据库文件路径
db_url = "configs/wattle.db"
# 工作者超时时间（秒）
worker_timeout_secs = 3600
# 最大并发工作者数量
max_concurrent_workers = 100

[database]
# 数据库最大连接数
max_connections = 50
# 连接超时时间（秒）
connection_timeout_secs = 30
# 连接空闲超时时间（秒）
idle_timeout_secs = 600

[logging]
# 日志级别：trace, debug, info, warn, error
level = "info"
# 日志文件路径
file_path = "logs/wattle.log"
# 单个日志文件最大大小（字节）
max_file_size = 10485760
# 保留的日志文件数量
max_files = 5

[execution]
# 执行日志存储目录
log_dir = "logs"
# 默认任务超时时间（秒，0表示无超时）
timeout_secs = 0
# 最大并行任务数
max_parallel_tasks = 10
