[package]
name = "runtime"
version.workspace = true
edition.workspace = true

[dependencies]
core = { path = "../core" }
eyre ={ workspace = true}
tracing = { workspace = true }
tokio ={ workspace = true}

[dev-dependencies]
tempfile = "*"