[package]
name = "runtime"
version.workspace = true
edition.workspace = true

[dependencies]
core = { path = "../core" }
eyre.workspace = true
tokio.workspace = true
async-stream = "0.3"
tracing = "0.1"
shell-words = "1.1"
